export { createWeeksmith, type CreateWeeksmithOptions } from "./agent.js";
export { createConsultSmith, type CreateConsultSmithOptions } from "./agent-consult.js";
export { runBuildThisWeek, type BuildThisWeekInput, type BuildThisWeekResult } from "./workflow.js";
export { runConsultThenBuild, type ConsultThenBuildInput, type ConsultThenBuildResult, type ConsultDeps } from "./workflow-consult.js";
export { defaultModel, getModel, openaiClient } from "./providers/openai.js";
export type { WeeksmithEffort } from "./providers/openai.js";
export { langfuse, tracing } from "./tracing.js";
export { BASE_INSTRUCTIONS } from "./prompts/base-instructions.js";
export { CONSULT_INSTRUCTIONS } from "./prompts/consult-instructions.js";
export { createNotesServer } from "./notes/server.js";
export { connectNotesMcp, type NotesMcpConnection } from "./notes/client.js";
export type { NotesStore, WeekStore, LogStore } from "./ports.js";
export type { WeeksmithStores } from "./tools/index.js";
export type { ConsultStores } from "./tools/consult.js";
export { memoryLogStore } from "./store-log-memory.js";
